#!/usr/bin/env bash
# deploy.sh — Deploy the Enterprise Knowledge Base RAG infrastructure and application.
set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────────────
STACK_NAME="${STACK_NAME:-enterprise-kb-rag}"
REGION="${AWS_REGION:-us-east-1}"
TEMPLATE_FILE="$(dirname "$0")/cloudformation/template.yaml"
OPENSEARCH_INDEX="enterprise-knowledge-base"

echo "================================================================"
echo " Enterprise Knowledge Base RAG — Deployment"
echo " Stack  : $STACK_NAME"
echo " Region : $REGION"
echo "================================================================"

# ── 1. Validate the CloudFormation template ───────────────────────────────────
echo ""
echo "[1/5] Validating CloudFormation template..."
aws cloudformation validate-template \
    --template-body file://"$TEMPLATE_FILE" \
    --region "$REGION" > /dev/null
echo "      Template valid."

# ── 2. Deploy / update the stack ─────────────────────────────────────────────
echo ""
echo "[2/5] Deploying CloudFormation stack (this may take a few minutes)..."
aws cloudformation deploy \
    --template-file "$TEMPLATE_FILE" \
    --stack-name "$STACK_NAME" \
    --capabilities CAPABILITY_NAMED_IAM \
    --region "$REGION" \
    --parameter-overrides \
        ProjectName="$STACK_NAME" \
    --no-fail-on-empty-changeset
echo "      Stack deployed."

# ── 3. Retrieve stack outputs ─────────────────────────────────────────────────
echo ""
echo "[3/5] Retrieving stack outputs..."

get_output() {
    aws cloudformation describe-stacks \
        --stack-name "$STACK_NAME" \
        --region "$REGION" \
        --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
        --output text
}

BUCKET_NAME=$(get_output "DocumentBucketName")
DYNAMO_TABLE=$(get_output "QueryHistoryTableName")
OPENSEARCH_ENDPOINT=$(get_output "OpenSearchCollectionEndpoint")
SNS_TOPIC_ARN=$(get_output "SNSTopicArn")
APP_ROLE_ARN=$(get_output "AppRoleArn")

echo "      S3 Bucket      : $BUCKET_NAME"
echo "      DynamoDB Table : $DYNAMO_TABLE"
echo "      OpenSearch     : $OPENSEARCH_ENDPOINT"
echo "      SNS Topic      : $SNS_TOPIC_ARN"
echo "      App Role ARN   : $APP_ROLE_ARN"

# ── 4. Create the OpenSearch k-NN index ───────────────────────────────────────
echo ""
echo "[4/5] Creating OpenSearch k-NN index (requires AWS SigV4 signing)..."

python3 - <<PYEOF
import boto3, json, urllib3
from botocore.auth import SigV4Auth
from botocore.awsrequest import AWSRequest
import botocore.session as bs

endpoint = "${OPENSEARCH_ENDPOINT}"
index    = "${OPENSEARCH_INDEX}"
region   = "${REGION}"

index_body = {
    "settings": {"index": {"knn": True, "knn.algo_param.ef_search": 100}},
    "mappings": {
        "properties": {
            "embedding":   {"type": "knn_vector", "dimension": 1536,
                            "method": {"name": "hnsw", "space_type": "innerproduct",
                                       "engine": "faiss"}},
            "content":     {"type": "text"},
            "document_id": {"type": "keyword"},
            "chunk_index": {"type": "integer"},
            "filename":    {"type": "keyword"},
            "category":    {"type": "keyword"},
            "tags":        {"type": "keyword"},
            "indexed_at":  {"type": "date"},
        }
    },
}

url     = f"{endpoint}/{index}"
session = bs.get_session()
creds   = session.get_credentials()
request = AWSRequest(method="PUT", url=url, data=json.dumps(index_body),
                     headers={"Content-Type": "application/json"})
SigV4Auth(creds, "aoss", region).add_auth(request)

http = urllib3.PoolManager()
resp = http.request("PUT", url, body=json.dumps(index_body), headers=dict(request.headers))

if resp.status in (200, 201):
    print("      Index created successfully.")
elif resp.status == 400 and b"already exists" in resp.data:
    print("      Index already exists — skipping.")
else:
    print(f"      WARNING: index creation returned HTTP {resp.status}: {resp.data.decode()}")
PYEOF

# ── 5. Write .env file ────────────────────────────────────────────────────────
echo ""
echo "[5/5] Writing .env configuration file..."
ENV_FILE="$(dirname "$0")/../.env"

cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
AWS_REGION=$REGION
S3_BUCKET=$BUCKET_NAME
OPENSEARCH_ENDPOINT=$OPENSEARCH_ENDPOINT
OPENSEARCH_INDEX=$OPENSEARCH_INDEX
BEDROCK_MODEL_ID=anthropic.claude-sonnet-4-6
BEDROCK_EMBED_MODEL_ID=amazon.titan-embed-text-v2:0
DYNAMODB_TABLE=$DYNAMO_TABLE
SNS_TOPIC_ARN=$SNS_TOPIC_ARN
CHUNK_SIZE=1000
CHUNK_OVERLAP=200
TOP_K_RESULTS=5
SIMILARITY_THRESHOLD=0.7
EOF

echo "      .env written to $ENV_FILE"

echo ""
echo "================================================================"
echo " Deployment complete!"
echo " Start the app with:  python app.py"
echo " API docs available at http://localhost:8000/docs"
echo "================================================================"
